# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jasonc/centos7"
  #Added the following line to fix "vagrant up" issue
   config.vm.provider "virtualbox" do | vb |
     vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
   end
  # VM properties
  config.vm.define "test1" do |test1|
    test1.vm.hostname = "test1"
    test1.vm.network "private_network", ip: "10.9.8.5"
  end
  config.vm.define "test2" do |test2|
    test2.vm.hostname = "test2"
    test2.vm.network "private_network", ip: "10.9.8.6"
  end
end
